### ISSUE TITLE
Fails in latest (1.3.x) game versions

### ISSUE THREAD

**Issue by lynnpye** [RealityMachina/Champion-Feats#4]
Pull request https://github.com/RealityMachina/Champion-Feats/pull/3 created to resolve the issue

**Comment by Frost212** [comment]
Please please please, update this for 1.4x. Have a few runs in progress that i can't finish because of this mod being broken =/

**Comment by lynnpye** [comment]
I've created a forked version on nexus, Champion Feats Anew

**Comment by lynnpye** [comment]
I've closed the PR
